arr = new Array(1,2,3,4,5)
arr.push(6)
console.log("after pushing 6 : "+arr)
arr.pop()
console.log("after poping : "+arr)
arr.shift()
console.log("after shifting"+arr)
arr.unshift(7,8)
console.log("after unshifting 0"+arr)
arr.splice(0,2,0,1,7,8)
console.log("after splicing : "+arr)