import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <header style={{backgroundColor:"lightblue"}}>
        <p>This is a Header</p>
      </header>
    
    {children}

    <footer style={{backgroundColor:"grey"}}>
      <p>This is a Footer</p>
    </footer></body>
      
    </html>
  );
}
